[fix] embedded ES
ServiceConfigurationError: An SPI class of type org.apache.lucene.analysis.util.TokenFilterFactory with classname org.apache.lucene.analysis.c
n.ChineseFilterFactory does not exist, please fix the file 'META-INF/services/org.apache.lucene.analysis.util.TokenFilterFactory' in your classpath.